Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: indykaraoke.com
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: errorpages/404.html
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: IndyKaraokeComStaticContentS3BucketPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource:
            Fn::Join:
              - 'arn:aws:s3:::'
              - Ref: S3Bucket
              - "/*"
      Bucket:
        Ref: S3Bucket
