---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: jle-config
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        -
          Key: Name
          Value: Global config management
