AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VPCId:
    Description: VPC to create the security group into
    Type: AWS::EC2::VPC::Id
    Default: vpc-55c2b13c

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Description: Jenkins Web Access Security Group
    Properties:
      GroupDescription: SSH from Home
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 8900
          ToPort: 8900
          IpProtocol: tcp
      VpcId: !Ref VPCId

Outputs:
  GroupId:
    Description: Id for security group
    Value: !GetAtt SecurityGroup.GroupId
